### ISSUE TITLE
Search results from HAC minutes

### ISSUE THREAD

**Issue by awmarrs** [HistoryAtState/hac#2]
Hey @joewiz for some reason I am getting zero hits when I restrict my search to the "about" section (in a recent effort to find something in the HAC minutes).

I searched for the words "transfer" and "NARA" which returned zero hits:

https://history.state.gov/search?q=transfer&within=about

But they are clearly in the August 2016 minutes (and doubtless elsewhere, but August 2016 are the most recent posted:

https://history.state.gov/about/hac/august-2016

I'm not sure why this would be the case, but at least wanted to bring it to your attention.

Thanks,
Aaron

**Comment by joewiz** [comment]
Fixed, at long last, by https://github.com/HistoryAtState/hac/commit/0d64afc2e1b5082738dfe17afc91bcb794b02b4b. 

Thanks, Aaron!
